### ISSUE TITLE
The wagon tries to push with wrong username

### ISSUE THREAD

**Issue by nicoulaj** [khuxtable/wagon-gitsite#6]
I had to add this to my settings.xml to have the site deployment working:

```
<server>
  <id>github</id> <!-- = site id in the distributionManagement section -->
  <username>git</username>
</server>
```

Otherwise, it tries to use my username (`nicoulaj`) instead of `git` to push to the remote repository, which is the username to use when pushing over SSH.

Full debug log [here](https://gist.github.com/749215) (tested with both Maven 3.0 and 2.2.1).

**Comment by khuxtable** [comment]
Yes, I have to include that as well. I consider this to be a documentation error.

**Comment by stephenc** [comment]
https://github.com/khuxtable/wagon-gitsite/commit/255b31797171a5af50f15dff16017487a2709806

has the documentation fix but until you publish a new version of the site to tie up with the 0.3.1 release this issue cannot be resolved ;-)

**Comment by khuxtable** [comment]
And when I try site:deploy I get

[INFO] [site:deploy {execution: default-cli}]
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Unsupported protocol: 'gitsite'

Embedded error: Cannot find wagon which supports the requested protocol: gitsite
Component descriptor cannot be found in the component repository: org.apache.maven.wagon.Wagongitsite.

This isn't due to the new version having a problem because I am now getting the same error with version 0.2, so obviously something in my environment has changed.

**Comment by nicoulaj** [comment]
Yes, version 0.3.1 is working fine for me.

**Comment by khuxtable** [comment]
Okay, I'll figure my environment out later. I manually pushed. Quite frustrating, since this is exactly what wagon-gitsite is supposed to do.

The documentation has been pushed.

**Comment by nicoulaj** [comment]
If this can help, I bumped the scm provider wagons versions too compared to what is said in the doc:
https://github.com/nicoulaj/bench-tool/blob/master/pom.xml#L367

**Comment by khuxtable** [comment]
That did not make a difference. This was working when last I did any documentation pushes to github, which would be sometime last August or September. I'm baffled.

**Comment by khuxtable** [comment]
BTW, the wagon works with all my other projects. Maybe it has something to do with it pushing itself, as it were...

**Comment by stephenc** [comment]
You should use the previous released version of the wagon in the projects pom.

Otherwise you have the current build depending on itself which is a circular dependency and causes issues.

Maven 3 would give out to you about doing that, but Maven 2 IIRC will blythly continue on and just fail

**Comment by khuxtable** [comment]
Yeah, I can see that. But if I've already installed the jar for the current version of the wagon in my local repo, why shouldn't it be allowed to work? That's just a rhetorical question, BTW, I will bow to reality.

**Comment by stephenc** [comment]
Because it resolves from the reactor.  Call it a bug... call it design.... M3 prevents you from having such a circle in the first place

**Comment by khuxtable** [comment]
Okay, that makes sense.
